@base_url = http://localhost:3001

#### USERS ####
POST {{base_url}}/auth/signup
Content-Type: application/json

{
  "name": "Rebeca",
  "email": "rebeca@mail.com"
}

### Image uploads
####
POST {{base_url}}/auth/upload

# pass on 'file' field